//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop_FoodXYZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_transaksi
    {
        public int id_transaksi { get; set; }
        public string no_transaksi { get; set; }
        public System.DateTime tgl_transaksi { get; set; }
        public long total_bayar { get; set; }
        public int id_user { get; set; }
        public int id_barang { get; set; }
    
        public virtual tbl_barang tbl_barang { get; set; }
        public virtual tbl_user tbl_user { get; set; }
    }
}
