//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UbigPost
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailTransaction
    {
        public int ID { get; set; }
        public int ItemID { get; set; }
        public int CountItem { get; set; }
        public double SubTotal { get; set; }
        public int TransactionID { get; set; }
    
        public virtual Transaction Transaction { get; set; }
        public virtual Item Item { get; set; }
    }
}
