//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Currency_converter
{
    using System;
    using System.Collections.Generic;
    
    public partial class USDExchangeRate
    {
        public int id { get; set; }
        public int period_id { get; set; }
        public int currency_id { get; set; }
        public decimal rate { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Period Period { get; set; }
    }
}
