//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seleknas_ASC_XII_2022___Dekstop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HOV_HospitalEntities : DbContext
    {
        public HOV_HospitalEntities()
            : base("name=HOV_HospitalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<doctor> doctors { get; set; }
        public virtual DbSet<doctor_category> doctor_category { get; set; }
        public virtual DbSet<icd_11> icd_11 { get; set; }
        public virtual DbSet<icd_11_doctor_recommendation> icd_11_doctor_recommendation { get; set; }
        public virtual DbSet<icd_11_exclusion> icd_11_exclusion { get; set; }
        public virtual DbSet<meeting> meetings { get; set; }
        public virtual DbSet<patient> patients { get; set; }
        public virtual DbSet<patient_record> patient_record { get; set; }
        public virtual DbSet<payment> payments { get; set; }
        public virtual DbSet<payment_detail> payment_detail { get; set; }
    }
}
