//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hov_hospital_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class icd_11_exclusion
    {
        public int id { get; set; }
        public int icd_11_id { get; set; }
        public string exclusion { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<System.DateTime> last_updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    
        public virtual icd_11 icd_11 { get; set; }
    }
}
