//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodXYZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_barang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_barang()
        {
            this.tbl_transaksi = new HashSet<tbl_transaksi>();
        }
    
        public int id_barang { get; set; }
        public string kode_barang { get; set; }
        public string nama_barang { get; set; }
        public System.DateTime expired_date { get; set; }
        public long jumlah_barang { get; set; }
        public string satuan { get; set; }
        public long harga_satuan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_transaksi> tbl_transaksi { get; set; }
    }
}
