//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int ticketID { get; set; }
        public int scheduleID { get; set; }
        public int departureStationID { get; set; }
        public System.DateTime departureTime { get; set; }
        public int arrivalStationID { get; set; }
        public System.DateTime arrivalTime { get; set; }
        public int seatNumber { get; set; }
        public string passengerName { get; set; }
        public decimal price { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
    
        public virtual Schedule Schedule { get; set; }
        public virtual Station Station { get; set; }
        public virtual Station Station1 { get; set; }
    }
}
